# Generated by Django 6.0.3 on 2026-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=5)),
                ('room_no', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'unique_together': {('block', 'room_no')},
            },
        ),
    ]
