# Generated by Django 6.0.1 on 2026-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='block',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
