# Generated by Django 6.0.3 on 2026-05-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
