# Generated by Django 6.0.3 on 2026-03-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0006_student_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('payment_method', models.CharField(max_length=30)),
                ('transaction_id', models.CharField(max_length=40)),
                ('receipt', models.FileField(upload_to='fee_receipt/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
