# Generated by Django 6.0.3 on 2026-03-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.CharField(default=-1, max_length=5),
            preserve_default=False,
        ),
    ]
