# Generated by Django 6.0.3 on 2026-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_fee_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='academic_year',
            field=models.CharField(max_length=10),
        ),
    ]
