# Generated by Django 6.0.1 on 2026-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_alter_fee_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=10),
        ),
    ]
