# Generated by Django 6.0.3 on 2026-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0005_remove_fee_due_date_alter_fee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='fee_receipt/'),
        ),
    ]
