# Generated by Django 6.0.3 on 2026-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('block', models.CharField(max_length=5)),
                ('room_no', models.CharField(max_length=10)),
                ('complaint', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
    ]
