# Generated by Django 6.0.3 on 2026-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
