# Generated by Django 6.0.3 on 2026-04-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaints_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='date',
        ),
    ]
