# Generated by Django 6.0.3 on 2026-04-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaints_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='block',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='description',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='name',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='room_no',
        ),
    ]
