# Generated by Django 6.0.3 on 2026-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_remove_complaints_block_remove_complaints_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='block',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
