# Generated by Django 6.0.3 on 2026-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaints_block_complaints_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
