# Generated by Django 6.0.3 on 2026-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaints_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('In progress', 'In progress')], default='Pending', max_length=20),
        ),
    ]
