# Generated by Django 6.0.3 on 2026-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaints_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
    ]
