# Generated by Django 6.0.3 on 2026-03-07 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_number', models.CharField(max_length=25, unique=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('course', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('guardian_name', models.CharField(max_length=30)),
                ('guardian_phone', models.IntegerField()),
                ('guardian_email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='students_photo/')),
                ('id_proof', models.FileField(upload_to='id_proof/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
