# Generated by Django 6.0.3 on 2026-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='+91', max_length=13),
        ),
    ]
