# Generated by Django 6.0.3 on 2026-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_course_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(default='+91', max_length=13),
        ),
    ]
