# Generated by Django 6.0.3 on 2026-04-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(default='+91', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='+91', max_length=15),
        ),
    ]
